# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('ext', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(1, 'Normal'), (0, 'Converting'), (-1, 'Deleted'), (-2, 'FileDeleted')], default=1)),
                ('page', models.PositiveIntegerField(null=True)),
                ('MD5', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=30)),
                ('views', models.PositiveIntegerField(default=0)),
                ('collects', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(null=True, upload_to='file')),
                ('pdf_path', models.FileField(null=True, upload_to='')),
                ('img_path', models.CharField(max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ManyToManyField(null=True, related_name='collects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='First_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_categories', to='Files.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('times', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Second_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('first_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_categories', to='Files.First_Category')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='second_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Files.Second_Category'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
